name: openhearthouse
favicon: null
layout_spectrum: 0.24637422105297446
typography_spectrum: 0.1394026931375265
title: Openhearthouse
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-69141509-8
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.1245983752887696
  lightness: 0.635620120447129
  saturation: 0.7211346516851336
  rhythmicContrast: 0.3924868556205183
purpose: []
