name: openhearthouse
favicon: null
layout_spectrum: 0.24637422105297446
typography_spectrum: 0.1394026931375265
title: Openhearthouse
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-69141509-8
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0ddcc'
    - '#6f5443'
    - '#40270c'
    - '#cb6c1f'
    - '#eea34f'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
