name: openhearthouse
favicon: null
layout_spectrum: 0.24637422105297446
typography_spectrum: 0.1394026931375265
title: Openhearthouse
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-69141509-8
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f4f7'
    - '#3c86a1'
    - '#123134'
    - '#abd313'
    - '#efc4b4'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
